contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #scmulti channel"
    url: https://nfcore.slack.com/channels/scmulti
    about: Discussion about the nf-core/scmulti pipeline
